version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /var/www/project/backend
    volumes:
      - ./backend:/var/www/project/backend
      - ./docker/jwt:/jwt
      - ./docker/backend.sh:/backend.sh
    entrypoint: /backend.sh
    environment:
      - XDEBUG_SESSION=1
      - PHP_IDE_CONFIG=serverName=project.local
    depends_on:
      - database
    networks:
      - web
    tty: true

  frontend:
    image: node:lts
    working_dir: /var/www/project/frontend
    volumes:
      - ./frontend:/var/www/project/frontend
      - ./docker/frontend.sh:/frontend.sh
      - ./frontend/var/log:/root/.npm/_logs
    entrypoint: /frontend.sh
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - web

  web_server:
    image: nginx
    volumes:
      - ./docker/conf/nginx/project.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/var/log/nginx:/var/log/nginx
      - .:/var/www/project
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - web

  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - web

volumes:
  pgdb:

networks:
  web:
